# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Extra formats
# PDF generation is failing for now; disabled on 2020-12-02
#formats:
#  - pdf

# Build documentation
sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
